---
- : Install nginx
  become: true
  ansible.builtin.apt:
    : ['nginx']
    state: present
    update_cache: true


- : Create nginx-config from template
  become: true
  template:
    src: Axon_nginx.conf.j2
    dest: /etc/nginx/sites-enabled/Axon.conf
    mode: "0777"


- : Create private key for self-signed certificate
  community.crypto.openssl_privatekey:
    path: "{{ Axon_ssl_key_path }}"
    type: RSA

- : Create simple self-signed certificate
  community.crypto.x509_certificate:
    path: "{{ Axon_ssl_cert_path }}"
    privatekey_path: "{{ Axon_ssl_key_path }}"
    provider: selfsigned


- : Restart nginx to apply config
  become: true
  ansible.builtin.service:
    : nginx
    state: restarted
