apiVersion: v1
metadata:
  : Axon-config
data:
  Axon.conf: |+
    [DEFAULT]
    debug = True
    log_path = "/var/log"
    database = "/etc/Axon/data/Axon_db"
    use_cuda = false

    [storage]
    dataset_location = "/etc/Axon/data/datasets"
    checkpoint_location = "/etc/Axon/data/checkpoints"
    tempfile_location = "/etc/Axon/data/tempfiles"
    tempfile_timeout = 10

    [processing]
    use_of_free_memory = {{ .Values.processing.use_of_free_memory }}

    [auth]
    policies = "/etc/Axon/policies"
    token_key_path = "/etc/Axon/token_key"
    token_expire_time = {{ .Values.token.expire_time }}

    [http]
    enable = True
    ip = 127.0.0.1
    port = 11418

kind: ConfigMap
