apiVersion: v1
kind: PersistentVolume
metadata:
  : Axon-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClass: Axon-sc
  hostPath:
    path: /etc/Axon_data/
