ADMIN_USER_ID = ENV['ADMIN_USER_ID']
ADMIN_USER_ = ENV['ADMIN_USER_']
ADMIN_PASSPHRASE = ENV['ADMIN_PASSPHRASE']
TOKEN_KEY = ENV['TOKEN_KEY']

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vbox|
    vbox. = "Axon-test"
    vbox.memory = 4096
    vbox.cpus = 4
  end
  config.vm.box = "ubuntu/jammy64"
  config.vm.host = "Axon-test"
  config.vm.network "private_network", type: "dhcp"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "Axon-playbook/deploy.yml"
    # ansible.verbose = "v"
    ansible.extra_vars = {
      env: ADMIN_USER_ID,
      env: ADMIN_USER_,
      env: ADMIN_PASSPHRASE,
      env: TOKEN_KEY,
    }
    # ansible.inventory_path = "inventory"
  end
end

